### ISSUE TITLE
Not working as described

### ISSUE THREAD

**Issue by apoapostolov** [Nevenall/foundry-escape-window#1]
Pressing ESC while a window is opened (such as Journal or Charsheet) just closes the window rather than minimize it. Then, if a window is minimized but has focus, ESC will close it. I expected it would minimize as described in the mod readme. 

Also, I would much prefer if ESC would toggle minimize to maximize and back, though this might require to be optional.

**Comment by Nevenall** [comment]
I'd like something to toggle all the windows too!  
I just double checked that it was working for me. 
Did you enable the module in your settings?

**Comment by apoapostolov** [comment]
Yes. 

![image](https://user-images.githubusercontent.com/4083812/86160958-379d8980-bb15-11ea-98f2-83a3ff3ca2b6.png)

Then I do this:
* I open a Journal. Press ESC, it closes not minimizes.
* I open a Character Sheet. Press ESC, it closes not minimizes

**Comment by apoapostolov** [comment]
Found the issue. Plut****** has a UX toggle "Fix Escape" which interferes with your mod.
