### ISSUE TITLE
Conflict with Monk's Enhanced Journal

### ISSUE THREAD

**Issue by Setting-Dawn** [Nevenall/foundry-escape-window#4]
It seems like recently a conflict with Monk's Enhanced Journal occurred. Since none of Monk's Enhanced Journal's files have changed in 28 days I assume it was something in this module as the modules were cooperating fine approximately two weeks ago. 

I'm running FoundryVTT 0.8.9 with DnD5e v. 1.4.2.
With only [Monk's Enhanced Journal 1.0.21] and [Foundry Escape Window 0.0.5] loaded, it is preventing me from opening Foundry's default ESC window at all. Only loading Foundry Escape Window by itself seems to work fine, and only loading Monk's Enhanced Journal by itself also works fine. However, both together seems to prevent the ESC key from opening the Menu. 

Luckily 3 of the 4 options on the menu can also be accessed in the Game Settings, but unfortunately Reload Application isn't accessible without using F5 while this conflict occurs.

**Comment by Nevenall** [comment]
Interesting, I'll take a look when I get the chance.

**Comment by Nevenall** [comment]
Whew that took some work! ;) Seems to be working now
