### ISSUE TITLE
No longer works under v9

### ISSUE THREAD

**Issue by dineshm72** [Nevenall/foundry-escape-window#5]
Not sure if it's keybind related or something else.

**Comment by Nevenall** [comment]
thanks, I will check it out
________________________________
From: dinesh ***@***.***>
Sent: Sunday, January 2, 2022 8:50 PM
To: Nevenall/foundry-escape-window ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Nevenall/foundry-escape-window] No longer works under v9 (Issue #5)


Not sure if it's keybind related or something else.

**Comment by dmrickey** [comment]
Came here to say the same thing

**Comment by Nevenall** [comment]
Fixed in version 1.0.0
